<?php

namespace Database\Seeders;

use App\Models\Brand;
use App\Models\Category;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Faker\Factory as Faker;

class ProductsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // $price = rand(1, 1000);
        // $discount = rand(1, 90);

        // DB::table('products')->insert(
        //     [
        //         [
        //             'title' => 'Shirt',
        //             'slug' => 'shirt',
        //             'short_description' => "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        //             'description' => "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        //             'cat_id' => 1,
        //             'brand_id' => 4,
        //             'child_cat_id' => 3,
        //             'vendor_id' => null,
        //             'price' => '500.00',
        //             'discount' => '10',
        //             'sale_price' => (500.00 - ((500.00 * 10) / 100)),
        //             'quantity' => rand(1, 5),
        //             'code' => Str::random(4),
        //             'size' => 'XL',
        //             'conditions' => 'new',
        //             'status' => 'show',
        //             'image_url1' => rand(1, 30) . '.jpg',
        //             'image_url2' => rand(1, 30) . '.jpg',
        //             'image_url3' => rand(1, 30) . '.jpg',
        //             'image_url4' => rand(1, 30) . '.jpg',
        //         ],
        //         [
        //             'title' => 'Lower',
        //             'slug' => 'lower',
        //             'short_description' => "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        //             'description' => "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        //             'cat_id' => 1,
        //             'brand_id' => 5,
        //             'child_cat_id' => 3,
        //             'vendor_id' => null,
        //             'price' => '800.00',
        //             'discount' => '60',
        //             'sale_price' => (800.00 - ((800.00 * 60) / 100)),
        //             'quantity' => rand(1, 5),
        //             'code' => Str::random(4),
        //             'size' => 'L',
        //             'conditions' => 'new',
        //             'status' => 'show',
        //             'image_url1' => rand(1, 30) . '.jpg',
        //             'image_url2' => rand(1, 30) . '.jpg',
        //             'image_url3' => rand(1, 30) . '.jpg',
        //             'image_url4' => rand(1, 30) . '.jpg',
        //         ],
        //         [
        //             'title' => 'Saree',
        //             'slug' => 'saree',
        //             'short_description' => "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        //             'description' => "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        //             'cat_id' => 2,
        //             'brand_id' => 4,
        //             'child_cat_id' => 4,
        //             'vendor_id' => null,
        //             'price' => '10000.00',
        //             'discount' => '60',
        //             'sale_price' => (10000.00 - ((10000.00 * 10) / 100)),
        //             'quantity' => rand(1, 5),
        //             'code' => Str::random(4),
        //             'size' => '',
        //             'conditions' => 'new',
        //             'status' => 'show',
        //             'image_url1' => rand(1, 30) . '.jpg',
        //             'image_url2' => rand(1, 30) . '.jpg',
        //             'image_url3' => rand(1, 30) . '.jpg',
        //             'image_url4' => rand(1, 30) . '.jpg',
        //         ],
        //         [
        //             'title' => 'Kurti',
        //             'slug' => 'kurti',
        //             'short_description' => "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        //             'description' => "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        //             'cat_id' => 2,
        //             'brand_id' => 4,
        //             'child_cat_id' => 4,
        //             'vendor_id' => null,
        //             'price' => '500.00',
        //             'discount' => '10',
        //             'sale_price' => (500.00 - ((500.00 * 10) / 100)),
        //             'quantity' => rand(1, 5),
        //             'code' => Str::random(4),
        //             'size' => 'XL',
        //             'conditions' => 'new',
        //             'status' => 'show',
        //             'image_url1' => rand(1, 30) . '.jpg',
        //             'image_url2' => rand(1, 30) . '.jpg',
        //             'image_url3' => rand(1, 30) . '.jpg',
        //             'image_url4' => rand(1, 30) . '.jpg',
        //         ],
        //         [
        //             'title' => 'Crop Top',
        //             'slug' => 'crop-top',
        //             'short_description' => "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        //             'description' => "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        //             'cat_id' => 2,
        //             'brand_id' => 4,
        //             'child_cat_id' => 4,
        //             'vendor_id' => null,
        //             'price' => '25000.00',
        //             'discount' => '80',
        //             'sale_price' => (25000.00 - ((25000.00 * 80) / 100)),
        //             'quantity' => rand(1, 5),
        //             'code' => Str::random(4),
        //             'size' => 'M',
        //             'conditions' => 'new',
        //             'status' => 'show',
        //             'image_url1' => rand(1, 30) . '.jpg',
        //             'image_url2' => rand(1, 30) . '.jpg',
        //             'image_url3' => rand(1, 30) . '.jpg',
        //             'image_url4' => rand(1, 30) . '.jpg',
        //         ],
        //         [
        //             'title' => 'Mobile',
        //             'slug' => 'mobile-phone',
        //             'short_description' => "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        //             'description' => "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        //             'cat_id' => 1,
        //             'brand_id' => 2,
        //             'child_cat_id' => 3,
        //             'vendor_id' => null,
        //             'price' => '50000.00',
        //             'discount' => '55',
        //             'sale_price' => (50000.00 - ((50000.00 * 55) / 100)),
        //             'quantity' => rand(1, 5),
        //             'code' => Str::random(4),
        //             'size' => '',
        //             'conditions' => 'new',
        //             'status' => 'show',
        //             'image_url1' => rand(1, 30) . '.jpg',
        //             'image_url2' => rand(1, 30) . '.jpg',
        //             'image_url3' => rand(1, 30) . '.jpg',
        //             'image_url4' => rand(1, 30) . '.jpg',
        //         ],
        //         [
        //             'title' => 'Mobile2',
        //             'slug' => 'mobile-phone2',
        //             'short_description' => "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        //             'description' => "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        //             'cat_id' => 1,
        //             'brand_id' => 2,
        //             'child_cat_id' => 3,
        //             'vendor_id' => null,
        //             'price' => '50000.00',
        //             'discount' => '55',
        //             'sale_price' => (50000.00 - ((50000.00 * 55) / 100)),
        //             'quantity' => rand(1, 5),
        //             'code' => Str::random(4),
        //             'size' => '',
        //             'conditions' => 'new',
        //             'status' => 'show',
        //             'image_url1' => rand(1, 30) . '.jpg',
        //             'image_url2' => rand(1, 30) . '.jpg',
        //             'image_url3' => rand(1, 30) . '.jpg',
        //             'image_url4' => rand(1, 30) . '.jpg',
        //         ],
        //         [
        //             'title' => 'Mobile3',
        //             'slug' => 'mobile-phone3',
        //             'short_description' => "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        //             'description' => "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        //             'cat_id' => 1,
        //             'brand_id' => 2,
        //             'child_cat_id' => 3,
        //             'vendor_id' => null,
        //             'price' => '50000.00',
        //             'discount' => '55',
        //             'sale_price' => (50000.00 - ((50000.00 * 55) / 100)),
        //             'quantity' => rand(1, 5),
        //             'code' => Str::random(4),
        //             'size' => '',
        //             'conditions' => 'new',
        //             'status' => 'show',
        //             'image_url1' => rand(1, 30) . '.jpg',
        //             'image_url2' => rand(1, 30) . '.jpg',
        //             'image_url3' => rand(1, 30) . '.jpg',
        //             'image_url4' => rand(1, 30) . '.jpg',
        //         ]
        //     ]
        // );
    }
}
